version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5433:5432"

  keycloak_ifood: # Segurança, usuários, oauth
    container_name: keycloak_ifood
    image: jboss/keycloak:16.1.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"

  jaeger_ifood: # Métricas das requisições e queries no banco
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.31
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  prometheus_ifood: # Métricas técnicas
    container_name: prometheus_ifood
    image: prometheus-ifood
    network_mode: "host" # Pra rodar como se o prometheus tivesse na máquina

  grafana_ifood: # Plataforma de visualização de métricas como a do Prometheus
    container_name: grafana_ifood
    image: grafana/grafana-oss:8.5.0-51396pre-ubuntu
    network_mode: "host"