-- localizacao definition

-- Drop table

-- DROP TABLE localizacao;

CREATE TABLE localizacao (
	id_localizacao int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nr_latirude numeric(19, 2) NULL,
	nr_longitude numeric(19, 2) NULL,
	CONSTRAINT localizacao_pkey PRIMARY KEY (id_localizacao)
);


-- restaurante definition

-- Drop table

-- DROP TABLE restaurante;

CREATE TABLE restaurante (
	id_restaurante int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	dt_atualizacao timestamp NULL,
	dt_criacao timestamp NULL,
	ds_nome varchar(255) NULL,
	nr_cnpj varchar(255) NULL,
	ds_proprietario varchar(255) NULL,
	id_localizacao int8 NULL,
	CONSTRAINT restaurante_pkey PRIMARY KEY (id_restaurante),
	CONSTRAINT fk7x9bkqoo9amitp1mmv9s9dlaa FOREIGN KEY (id_localizacao) REFERENCES localizacao(id_localizacao)
);


-- prato definition

-- Drop table

-- DROP TABLE prato;

CREATE TABLE prato (
	id_prato int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	ds_descricao varchar(255) NULL,
	ds_nome varchar(255) NULL,
	nr_preco numeric(19, 2) NULL,
	id_restaurante int8 NULL,
	CONSTRAINT prato_pkey PRIMARY KEY (id_prato),
	CONSTRAINT fkj74j9gjk32uduxnx4dq6ydwqx FOREIGN KEY (id_restaurante) REFERENCES restaurante(id_restaurante)
);